// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgYScf1giacL_9wAzFL0ZaLClvzOi3rRo',
    appId: '1:868061640964:android:d81d9e584d9725642cb851',
    messagingSenderId: '868061640964',
    projectId: 'freedom-main-app',
    storageBucket: 'freedom-main-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv4QMxAWTzxiT7ufdEUvTdRYSpAcGtZDU',
    appId: '1:868061640964:ios:3f0503162b96fe372cb851',
    messagingSenderId: '868061640964',
    projectId: 'freedom-main-app',
    storageBucket: 'freedom-main-app.firebasestorage.app',
    androidClientId: '868061640964-ikrmbkeq8jorovt3rvo1hkssfb5rh5ig.apps.googleusercontent.com',
    iosClientId: '868061640964-pl1mon3tb7kj5kpgp8ch7ihdfj7s0mg0.apps.googleusercontent.com',
    iosBundleId: 'com.freedom.app.freedom',
  );

}